version: "3"

services:

  rails:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: >
      /bin/sh -c "bundle install &&
                  npm install &&
                  rm -f /app/tmp/pids/server.pid &&
                  rails s puma -p 3000 -b '0.0.0.0'"
    user: ${CURRENT_UID}
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
